name: "Flarum L10N"

on:
  schedule:
    - cron:  "0 22 * * *"

  # workflow_dispatch:

jobs:
  l10n:
    runs-on: ubuntu-latest
    name: "[L10N] AUTO-UPDATE"
    steps:
      - uses: "pkgstore/github-action-flarum-l10n@main"
        with:
          repo: "https://github.com/${{ github.repository }}.git"
          user: "${{ secrets.GIT_BOT_NAME }}"
          email: "${{ secrets.GIT_BOT_EMAIL }}"
          token: "${{ secrets.GIT_BOT_TOKEN }}"
